### ISSUE TITLE
Recommend runInBand

### ISSUE THREAD

**Issue by haines** [KnapsackPro/knapsack-pro-jest#24]
I think it'd make sense to recommend configuring Jest with `runInBand` in the installation guide, because knapsack-pro-jest invokes the Jest CLI repeatedly, so forking worker processes for each subset adds a lot of overhead.

For our test suite:

| command | options | total time |
|---|---|---|
| `jest` | `runInBand` | 25m52s |
| `jest` | `maxWorkers=2` | 20m18s |
| `knapsack-pro-jest` | `runInBand` | 32m0s |
| `knapsack-pro-jest` | `maxWorkers=2` | 77m18s |

Would it be feasible for knapsack-pro-jest to hook in at a lower level so that it would be possible to run with multiple worker processes? As you can see, it makes a big difference for our suite.

**Comment by ArturT** [comment]
How is the total time measured? Is this data from the Knapsack Pro user dashboard for a CI build view? Or it's total time from your CI provider dashboard?

Did you test [`runInBand`](https://jestjs.io/docs/en/cli#--runinband) this way `$(npm bin)/knapsack-pro-jest --runInBand` ? 

Could you provide git commit hash for your CI build with `runInBand` and without it so I could review data in knapsack pro dashboard?


> Would it be feasible for knapsack-pro-jest to hook in at a lower level so that it would be possible to run with multiple worker processes?

This is how `jest.runCLI` is called in `@knapsack-pro/jest`.
https://github.com/KnapsackPro/knapsack-pro-jest/blob/4373d8852582822c47bb7987e9046630af2ab283/src/knapsack-pro-jest.ts#L46

Here is a list of CLI options available to pass https://jestjs.io/docs/en/cli

Example of how to pass options https://knapsackpro.com/faq/question/how-to-pass-command-line-options-to-jest

You could pass `--maxWorkers` option to the knapsack: `$(npm bin)/knapsack-pro-jest --maxWorkers=2`
https://jestjs.io/docs/en/cli#--maxworkersnumstring


BTW Isn't `--runInBand` equivalent of using `--maxWorkers=1`?

**Comment by haines** [comment]
>How is the total time measured? Is this data from the Knapsack Pro user dashboard for a CI build view? Or it's total time from your CI provider dashboard?

The `jest` measurements are taken from the summary at the end of the suite, e.g.

```
Test Suites: 757 passed, 757 total
Tests:       3400 passed, 3400 total
Snapshots:   62 passed, 62 total
Time:        1218.09 s
Ran all test suites.
```

The `knapsack-pro-jest` measurements are taken from the Knapsack Pro user dashboard "total time execution", for these builds:

- [`runInBand`](https://knapsackpro.com/dashboard/organizations/1664/projects/1235/test_suites/1757/builds/c7ab81e0-27a6-4f91-a001-27d6bc9de9d5)
- [`maxWorkers=2`](https://knapsackpro.com/dashboard/organizations/1664/projects/1235/test_suites/1757/builds/9d1ee645-3c19-4632-a8e8-9a7da2afdbac)

>Did you test `runInBand` this way `$(npm bin)/knapsack-pro-jest --runInBand`?
>You could pass `--maxWorkers` option to the knapsack: `$(npm bin)/knapsack-pro-jest --maxWorkers=2`

Yep, this is how we performed the measurements

```
# on a single node
$(npm bin)/jest --runInBand
$(npm bin)/jest --maxWorkers=2

# across 8 nodes
$(npm bin)/knapsack-pro-jest --runInBand
$(npm bin)/knapsack-pro-jest --maxWorkers=2
```

>BTW Isn't `--runInBand` equivalent of using `--maxWorkers=1`?
Yep, it is. I think they provide `runInBand` as a separate option because it more accurately describes what's happening - it doesn't use forked worker processes but rather runs the tests in the main process.

>This is how `jest.runCLI` is called in `@knapsack-pro/jest`.

I think the problem with calling `jest.runCLI` for each queue subset is that Jest won't reuse the worker processes, which means setting `maxWorkers` above 1 causes new workers to be forked every time. If there isn't a simple way to hook into Jest at a lower level so that it doesn't fork new workers for each subset, I think the best thing to do would be to add a recommendation to the documentation / FAQs to recommend setting `runInBand` to avoid this problem.

**Comment by ArturT** [comment]
Thanks @haines 

I've updated readme https://github.com/KnapsackPro/knapsack-pro-jest/pull/25
