### ISSUE TITLE
Force exit doesn't work

### ISSUE THREAD

**Issue by lzientek** [KnapsackPro/knapsack-pro-jest#31]
Hello,
I run my tests on the CI using
`knapsack-pro-jest --forceExit --detectOpenHandles --runInBand`

Using only jest the forceExit worked fine but when using knapsack-pro-jest the forceExit option doesn't end the test suite and hangs indefinitely.

Sadly I can't send you some of my code.

**Comment by ArturT** [comment]
Hi @lzientek 

Here is a related FAQ topic 
https://knapsackpro.com/faq/question/why-jest-freezes-after-tests-run-jest-hangs-indefinitely

You can also verify if you have enough memory on the CI server. Check this tip: 
https://knapsackpro.com/faq/question/javascript-heap-out-of-memory-how-to-increase-the-max-memory-for-node-with-max_old_space_size

`@knapsack-pro/jest` runs Jest multiple times for each set of tests fetched from Queue API. See source code https://github.com/KnapsackPro/knapsack-pro-jest/blob/c675ab647d8e23dd1b0b4e6f03baeacd66ab0e43/src/knapsack-pro-jest.ts#L46

Here you can learn more about how Queue Mode works with `@knapsack-pro/jest` client  https://docs.knapsackpro.com/2020/how-to-build-native-integration-with-knapsack-pro-api-to-run-tests-in-parallel-for-any-test-runner-testing-framework

> Sadly I can't send you some of my code.

You can share the output with me via support email https://knapsackpro.com/contact
What's your user email, so I can check things on my side?

Is everything hangs after the first set of tests fetched from Queue API is executed? Or you have only some specific test files that cause freeze?
Do you know what is causing the freeze?
Is `--detectOpenHandles` showing useful tips to debug and fix root problems?

**Comment by lzientek** [comment]
Probably a memory issue on our ci thanks for your answer.

**Comment by ArturT** [comment]
Thanks for the info. You can try this https://knapsackpro.com/faq/question/javascript-heap-out-of-memory-how-to-increase-the-max-memory-for-node-with-max_old_space_size and use more RAM on the CI node.
