### ISSUE TITLE
Jest 28 Breaks Npm Install

### ISSUE THREAD

**Issue by daaasbu** [KnapsackPro/knapsack-pro-jest#50]
The current peer dependency breaks npm install if you upgrade to jest 28 but knapsack still seems to work with the latest version. Could you change the peer dependency to just be `jest": ">=22.0.0"`  instead?

**Comment by ArturT** [comment]
@daaasbu I've released a new version of `@knapsack-pro/jest` 5.3.0. Please update it in your project.
