### ISSUE TITLE
Jest 29 support

### ISSUE THREAD

**Issue by MarcEspiard** [KnapsackPro/knapsack-pro-jest#63]
Hi,

Is there a specific reason jest 29 is excluded in the dependencies? Any chance we could get a version that works with it please? 
It's preventing us from updating to jest v29.

Cheers
Marc

**Comment by ArturT** [comment]
Hi @MarcEspiard 

What error do you see? Is it similar to this one https://github.com/KnapsackPro/knapsack-pro-cypress/issues/89#issuecomment-1412699931

If it's a warning, you can ignore it.

I need to update `peerDependencies` in https://github.com/KnapsackPro/knapsack-pro-jest/blob/a4328d2b56582dca7722b8649c1a44a0bf80728f/package.json#L62

**Comment by MarcEspiard** [comment]
Hey, npm is blocking the jest upgrade due to this package depency to jest < 29
I can force it to pass but I'd rather not.
Can you make a release once you have confirmed it works with jest 29 and updated the dependency please?

**Comment by ArturT** [comment]
> Can you make a release once you have confirmed it works with jest 29 and updated the dependency please?

I have it in my backlog. I'll get back to you when it's ready.

**Comment by ArturT** [comment]
A new version of the `@knapsack-pro/jest` package has been released. Please update to 5.5.0.
